/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package archdoc.docmanager;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Gustavo Paiva
 */
public class AnaliseView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AnaliseView
     */
    public AnaliseView() throws IOException {
        initComponents();
           
    }
    
    public void arrumaImagem(){
        jLabel2.setIcon(new ImageIcon(System.getProperty("user.dir") + "/Python/retorno.png"));
        
        //while(this.getHeight() == 0 || this.getWidth() == 0)
        
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(System.getProperty("user.dir") + "/Python/retorno.png"));
        } catch (IOException e) {
            System.out.println("ERRO e: " + e);
        }
        
        Image dimg = null;
        
        try{
            System.out.println("ALTURA: " + this.getHeight());
            System.out.println("LARGURA: " + this.getWidth());
            System.out.println("PROTOCOLO: Image.SCALE_AREA_AVERAGING");
            
            dimg = img.getScaledInstance(this.getHeight() - 15, this.getWidth() - 15, Image.SCALE_AREA_AVERAGING);
        }catch(Exception e){
            System.out.println("Erro ao redimensionar a imagem " + e);
        }
        
        try{
            ImageIcon imageIcon = new ImageIcon(dimg);

            jLabel2.setIcon(imageIcon);
            jLabel2.repaint();
            
        }catch(Exception e){
            System.out.println("ERRO");
        }
        
        /*
        BufferedImage resizeImage(BufferedImage originalImage, int targetWidth, int targetHeight) throws IOException {
        BufferedImage resizedImage = new BufferedImage(targetWidth, targetHeight, BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics2D = resizedImage.createGraphics();
        graphics2D.drawImage(originalImage, 0, 0, targetWidth, targetHeight, null);
        graphics2D.dispose();*/
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                fechar(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechar(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_fechar
        // TODO add your handling code here:
                    new File(System.getProperty("user.dir") + "/Python/retorno.png").delete();
    }//GEN-LAST:event_fechar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
