/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package archdoc.docmanager;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

public class tela_trabalho extends javax.swing.JFrame {

    /**
     * Creates new form tela_inicial
     */
    private String htmlSobre = System.getProperty("user.dir") + "\\HTML\\Sobre\\index.html";
    private String htmlAjuda = System.getProperty("user.dir") + "\\HTML\\Ajuda\\index.html";
    private tiposArquivos popup_tiposArquivos;
    tela_trabalho2 trabalhoAtual;
    tela_trabalho1 trabalhoNovo;
    boolean darkMode = false;
    boolean atualizou = false;
    Info telinha;
    Config popup_config;

    public boolean isAtualizou() {
	return atualizou;
    }

    public void setAtualizou(boolean atualizou) {
	this.atualizou = atualizou;
    }

    public boolean isDarkMode() {
	return darkMode;
    }

    public void setDarkMode(boolean darkMode) {
	this.darkMode = darkMode;
    }

    public static Rectangle getMaximumScreenBounds() {
	int minx = 0, miny = 0, maxx = 0, maxy = 0;
	GraphicsEnvironment environment = GraphicsEnvironment.getLocalGraphicsEnvironment();
	for (GraphicsDevice device : environment.getScreenDevices()) {
	    Rectangle bounds = device.getDefaultConfiguration().getBounds();
	    minx = Math.min(minx, bounds.x);
	    miny = Math.min(miny, bounds.y);
	    maxx = Math.max(maxx, bounds.x + bounds.width);
	    maxy = Math.max(maxy, bounds.y + bounds.height);
	}
	return new Rectangle(minx, miny, maxx - minx, maxy - miny);
    }

    public tela_trabalho() {
	initComponents();
	setExtendedState(MAXIMIZED_BOTH);

	this.setContentPane(pane_telaprincipal);
	Toolkit kit = Toolkit.getDefaultToolkit();
	Dimension tamTela = kit.getScreenSize();

	int larg = tamTela.width;
	int alt = tamTela.height;
	setSize(larg, alt);

	System.out.println(getMaximumScreenBounds().getWidth());
	System.out.println(getMaximumScreenBounds().getHeight());

	Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(System.getProperty("user.dir") + "\\imgs\\icons\\principal.png");
	setIconImage(iconeTitulo);

	trabalhoNovo = new tela_trabalho1(atualizou);
	pane_telaprincipal.add(trabalhoNovo);

	trabalhoAtual = new tela_trabalho2();
	pane_telaprincipal.add(trabalhoAtual);

	trabalhoAtual.setVisible(true);
	trabalhoNovo.setVisible(true);

	pane_telaprincipal.setSize(this.getWidth(), this.getHeight());

	trabalhoAtual.setSize(pane_telaprincipal.getWidth() / 2, pane_telaprincipal.getHeight());
	trabalhoNovo.setSize(pane_telaprincipal.getWidth() / 2, pane_telaprincipal.getHeight());

	trabalhoNovo.setLocation(0, 0);
	trabalhoAtual.setLocation(trabalhoNovo.getWidth(), 0);

	trabalhoNovo.setLocal(trabalhoNovo.getLocation());
	trabalhoAtual.setLocal(trabalhoAtual.getLocation());

	setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane_telaprincipal = new javax.swing.JDesktopPane();
        menu_telatrabalho = new javax.swing.JMenuBar();
        menutrabalho_logo = new javax.swing.JMenu();
        menutrabalho_separador2 = new javax.swing.JMenu();
        menutrabalho_salvar = new javax.swing.JMenu();
        menutrabalho_separador5 = new javax.swing.JMenu();
        menutrabalho_exportar = new javax.swing.JMenu();
        menutrabalho_separador6 = new javax.swing.JMenu();
        menutrabalho_opcoes = new javax.swing.JMenu();
        menuItem_Tipos = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuitem_sobre = new javax.swing.JMenuItem();
        menuitem_ajuda = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menutrabalho_separador1 = new javax.swing.JMenu();
        menutrabalho_usuario = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DocManager - Plataforma de Operação");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1245, 639));

        pane_telaprincipal.setPreferredSize(new java.awt.Dimension(1245, 639));
        pane_telaprincipal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                mudouTamanho(evt);
            }
        });

        javax.swing.GroupLayout pane_telaprincipalLayout = new javax.swing.GroupLayout(pane_telaprincipal);
        pane_telaprincipal.setLayout(pane_telaprincipalLayout);
        pane_telaprincipalLayout.setHorizontalGroup(
            pane_telaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1245, Short.MAX_VALUE)
        );
        pane_telaprincipalLayout.setVerticalGroup(
            pane_telaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        menutrabalho_logo.setText("archDoc");
        menutrabalho_logo.setFocusable(false);
        menutrabalho_logo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menutrabalho_logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menutrabalho_logoMouseClicked(evt);
            }
        });
        menu_telatrabalho.add(menutrabalho_logo);

        menutrabalho_separador2.setText("|");
        menutrabalho_separador2.setEnabled(false);
        menutrabalho_separador2.setFocusable(false);
        menu_telatrabalho.add(menutrabalho_separador2);

        menutrabalho_salvar.setText("Salvar");
        menutrabalho_salvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menutrabalho_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menutrabalho_salvarMouseClicked(evt);
            }
        });
        menutrabalho_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutrabalho_salvarActionPerformed(evt);
            }
        });
        menu_telatrabalho.add(menutrabalho_salvar);

        menutrabalho_separador5.setText("|");
        menutrabalho_separador5.setEnabled(false);
        menutrabalho_separador5.setFocusable(false);
        menu_telatrabalho.add(menutrabalho_separador5);

        menutrabalho_exportar.setText("Exportar");
        menutrabalho_exportar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_telatrabalho.add(menutrabalho_exportar);

        menutrabalho_separador6.setText("|");
        menutrabalho_separador6.setEnabled(false);
        menutrabalho_separador6.setFocusable(false);
        menu_telatrabalho.add(menutrabalho_separador6);

        menutrabalho_opcoes.setText("Opções");
        menutrabalho_opcoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItem_Tipos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItem_Tipos.setText("Configurar tipos");
        menuItem_Tipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem_TiposMouseClicked(evt);
            }
        });
        menuItem_Tipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_TiposActionPerformed(evt);
            }
        });
        menutrabalho_opcoes.add(menuItem_Tipos);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Configurar revisões");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menutrabalho_opcoes.add(jMenuItem3);

        menuitem_sobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuitem_sobre.setText("Sobre");
        menuitem_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_sobreActionPerformed(evt);
            }
        });
        menutrabalho_opcoes.add(menuitem_sobre);

        menuitem_ajuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuitem_ajuda.setText("Ajuda");
        menuitem_ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_ajudaActionPerformed(evt);
            }
        });
        menutrabalho_opcoes.add(menuitem_ajuda);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Mudar Tema");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menutrabalho_opcoes.add(jMenuItem1);

        menu_telatrabalho.add(menutrabalho_opcoes);

        menutrabalho_separador1.setText("|");
        menutrabalho_separador1.setEnabled(false);
        menutrabalho_separador1.setFocusable(false);
        menu_telatrabalho.add(menutrabalho_separador1);

        menutrabalho_usuario.setText("Usuário");
        menutrabalho_usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menutrabalho_usuario.add(jMenuItem2);

        menu_telatrabalho.add(menutrabalho_usuario);

        setJMenuBar(menu_telatrabalho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_telaprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_telaprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void menuitem_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_sobreActionPerformed
	// TODO add your handling code here:
	try {
	    Desktop desktop = Desktop.getDesktop();
	    File htmlSobre_file = new File(htmlSobre);
	    desktop.open(htmlSobre_file);
	} catch (Exception erro) {
	    System.out.println(erro);
	}
    }//GEN-LAST:event_menuitem_sobreActionPerformed

    private void menuItem_TiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem_TiposMouseClicked
	// TODO add your handling code here
    }//GEN-LAST:event_menuItem_TiposMouseClicked

    private void menuItem_TiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_TiposActionPerformed
	// TODO add your handling code here:
	int lDesk = pane_telaprincipal.getWidth();
	int aDesk = pane_telaprincipal.getHeight();
	int lIFrame = this.getWidth();
	int aIFrame = this.getHeight();

	try {
	    if (!popup_tiposArquivos.isVisible()) {
		popup_tiposArquivos = new tiposArquivos(pane_telaprincipal, atualizou);
		pane_telaprincipal.add(popup_tiposArquivos);
		popup_tiposArquivos.setVisible(true);
		popup_tiposArquivos.moveToFront();

	    } else {
		popup_tiposArquivos.moveToFront();
	    }
	} catch (Exception e) {
	    popup_tiposArquivos = new tiposArquivos(pane_telaprincipal, atualizou);
	    pane_telaprincipal.add(popup_tiposArquivos);
	    popup_tiposArquivos.setVisible(true);
	    popup_tiposArquivos.moveToFront();
	}
    }//GEN-LAST:event_menuItem_TiposActionPerformed

    private void menuitem_ajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_ajudaActionPerformed
	// TODO add your handling code here:
	try {
	    Desktop desktop = Desktop.getDesktop();
	    File htmlAjuda_file = new File(htmlAjuda);
	    desktop.open(htmlAjuda_file);
	} catch (Exception erro) {
	    System.out.println(erro);
	}
    }//GEN-LAST:event_menuitem_ajudaActionPerformed

    private void menutrabalho_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutrabalho_salvarActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_menutrabalho_salvarActionPerformed

    private void menutrabalho_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutrabalho_salvarMouseClicked

    }//GEN-LAST:event_menutrabalho_salvarMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

	try {
	    if (javax.swing.UIManager.getLookAndFeel().getName() == "FlatLaf Darcula") {
		FlatLightLaf lookAndFeel1 = new FlatLightLaf();
		javax.swing.UIManager.setLookAndFeel(lookAndFeel1);
	    } else {
		FlatDarculaLaf lookAndFeel2 = new FlatDarculaLaf();
		javax.swing.UIManager.setLookAndFeel(lookAndFeel2);
	    }

	    for (java.awt.Frame f : java.awt.Frame.getFrames()) {
		javax.swing.SwingUtilities.updateComponentTreeUI(f);
	    }
	} catch (UnsupportedLookAndFeelException e) {
	    e.printStackTrace();
	}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menutrabalho_logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutrabalho_logoMouseClicked
	// TODO add your handling code here:
        try{
	    if(!telinha.isVisible()){
		telinha = new Info(pane_telaprincipal);
		pane_telaprincipal.add(telinha);
		telinha.setVisible(true);
		telinha.moveToFront();
	    }
	}catch(Exception e) { 
	    telinha = new Info(pane_telaprincipal);
	    pane_telaprincipal.add(telinha);
	    telinha.setVisible(true);
	    telinha.moveToFront(); 
	}
    }//GEN-LAST:event_menutrabalho_logoMouseClicked

    private void mudouTamanho(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mudouTamanho
	// TODO add your handling code here:
	try {
	    trabalhoAtual.setSize(pane_telaprincipal.getWidth() / 2, pane_telaprincipal.getHeight());
	    trabalhoNovo.setSize(pane_telaprincipal.getWidth() / 2, pane_telaprincipal.getHeight());

	    trabalhoNovo.setLocation(0, 0);
	    trabalhoAtual.setLocation(trabalhoNovo.getWidth(), 0);

	    trabalhoNovo.setLocal(trabalhoNovo.getLocation());
	    trabalhoAtual.setLocal(trabalhoAtual.getLocation());
	} catch (Exception e) {;
	}
    }//GEN-LAST:event_mudouTamanho

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String[] options = {"Sim", "Não", "Cancelar"};
        int i = JOptionPane.showOptionDialog(null, "Tem certeza que deseja sair?", "Menu do usuário",
                                        JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,
                                        null, options, options[0]);  
        
        if(i == 0) System.exit(0);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try{
	    if(!popup_config.isVisible()){
		popup_config = new Config(pane_telaprincipal);
		pane_telaprincipal.add(telinha);
		popup_config.setVisible(true);
		popup_config.moveToFront();
	    }
	}catch(Exception e) { 
	    popup_config = new Config(pane_telaprincipal);
	    pane_telaprincipal.add(popup_config);
	    popup_config.setVisible(true);
	    popup_config.moveToFront(); 
	}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    javax.swing.UIManager.setLookAndFeel(new FlatDarculaLaf());
	} catch (Exception ex) {
	    System.err.println("Failed to initialize LaF");
	}
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new tela_trabalho().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menuItem_Tipos;
    private javax.swing.JMenuBar menu_telatrabalho;
    private javax.swing.JMenuItem menuitem_ajuda;
    private javax.swing.JMenuItem menuitem_sobre;
    private javax.swing.JMenu menutrabalho_exportar;
    private javax.swing.JMenu menutrabalho_logo;
    private javax.swing.JMenu menutrabalho_opcoes;
    private javax.swing.JMenu menutrabalho_salvar;
    private javax.swing.JMenu menutrabalho_separador1;
    private javax.swing.JMenu menutrabalho_separador2;
    private javax.swing.JMenu menutrabalho_separador5;
    private javax.swing.JMenu menutrabalho_separador6;
    private javax.swing.JMenu menutrabalho_usuario;
    private javax.swing.JDesktopPane pane_telaprincipal;
    // End of variables declaration//GEN-END:variables
}
