/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package archdoc.docmanager;

import java.awt.Frame;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;


public class tela_login extends javax.swing.JInternalFrame {
    
    JDesktopPane telaPrincipal;
    boolean fezLogin = false;
    Connection conexao;
    connect criaBD;
    boolean darkMode;
    
    
    public tela_login(JDesktopPane telaPrincipal, Connection conexao, boolean darkMode) {
        initComponents();
        
        setFrameIcon(new ImageIcon(System.getProperty("user.dir") + "\\imgs\\icons\\login.png"));
        
        this.telaPrincipal = telaPrincipal;
        this.conexao = conexao;
        this.darkMode = darkMode;
        
        try{criaBD = new connect();
        }catch(Exception e){;}
        
        int lDesk = telaPrincipal.getWidth();  
	int aDesk = telaPrincipal.getHeight();  
	int lIFrame = this.getWidth();  
	int aIFrame = this.getHeight();  

	this.setLocation(lDesk / 2 - lIFrame / 2, aDesk / 2 - aIFrame / 2);
	
	campo_usuario1.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campo_usuario1 = new javax.swing.JTextField();
        label_usuario1 = new javax.swing.JLabel();
        label_senha1 = new javax.swing.JLabel();
        botao_entrar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        notas1 = new javax.swing.JTextPane();
        label_notas1 = new javax.swing.JLabel();
        campo_senha1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        mostrarSenha = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(28, 28, 39));
        setClosable(true);
        setTitle("Menu do Usuário");
        setMaximumSize(new java.awt.Dimension(751, 444));
        setMinimumSize(new java.awt.Dimension(751, 444));
        setPreferredSize(new java.awt.Dimension(751, 444));
        setVisible(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        campo_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_usuario1ActionPerformed(evt);
            }
        });

        label_usuario1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label_usuario1.setText("Usuário");

        label_senha1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label_senha1.setText("Senha");

        botao_entrar1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        botao_entrar1.setText("ENTRAR");
        botao_entrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_entrar1ActionPerformed(evt);
            }
        });

        notas1.setEditable(false);
        notas1.setText("Patch da versão 2.01.5.12 \nNota-se versão beta em vigor\nEm caso de dúvida acessar \"Ajuda\" em opções\nUsuários apenas cadastrados pelo administrador");
        notas1.setFocusable(false);
        jScrollPane2.setViewportView(notas1);

        label_notas1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label_notas1.setText("Notas");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        mostrarSenha.setText("Mostrar Senha");
        mostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_usuario1)
                    .addComponent(campo_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_senha1)
                    .addComponent(campo_senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarSenha)
                    .addComponent(botao_entrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_notas1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(label_usuario1)
                .addGap(6, 6, 6)
                .addComponent(campo_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_senha1)
                .addGap(6, 6, 6)
                .addComponent(campo_senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mostrarSenha)
                .addGap(18, 18, 18)
                .addComponent(botao_entrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(label_notas1)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_usuario1ActionPerformed

    private void botao_entrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrar1ActionPerformed
        // TODO add your handling code here:
        char[] password = campo_senha1.getPassword();
        
        if(criaBD.checkUser(conexao, campo_usuario1.getText(), String.valueOf(password))){
	    
            loading Carr = new loading();
            Carr.setVisible(true);
            dispose();
            this.fezLogin = true;
            for(Frame v : tela_principal.getFrames()){
                   if(v.getName().equals("frame0")) {
                       v.dispose();
                   }
            }
	}
    }//GEN-LAST:event_botao_entrar1ActionPerformed

    private void mostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaActionPerformed
        // TODO add your handling code here:
        //campo_senha1.setAction(Action);
        if(mostrarSenha.isSelected())
            campo_senha1.setEchoChar((char)0);
        else
            campo_senha1.setEchoChar('•');
	
	campo_senha1.grabFocus();
    }//GEN-LAST:event_mostrarSenhaActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        campo_usuario1.grabFocus();
    }//GEN-LAST:event_formFocusGained

    public boolean isFezLogin() {
        return fezLogin;
    }

    public void setFezLogin(boolean fezLogin) {
        this.fezLogin = fezLogin;
    }

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_entrar1;
    private javax.swing.JPasswordField campo_senha1;
    private javax.swing.JTextField campo_usuario1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_notas1;
    private javax.swing.JLabel label_senha1;
    private javax.swing.JLabel label_usuario1;
    private javax.swing.JCheckBox mostrarSenha;
    private javax.swing.JTextPane notas1;
    // End of variables declaration//GEN-END:variables
}
