/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package archdoc.docmanager;

import javax.swing.JDesktopPane;

/**
 *
 * @author super
 */
public class tela_principal extends javax.swing.JFrame {

    /**
     * Creates new form tela_inicial
     */
    tela_login telaCadUser;
    
    public tela_principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane_telaprincipal = new javax.swing.JDesktopPane();
        logo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menu_usuario = new javax.swing.JMenu();
        menuitem_login = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menu_opcoes = new javax.swing.JMenu();
        menuitem_sobre = new javax.swing.JMenuItem();
        menuitem_ajuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\super\\Downloads\\Group 4 (2).png")); // NOI18N
        logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        pane_telaprincipal.setLayer(logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pane_telaprincipalLayout = new javax.swing.GroupLayout(pane_telaprincipal);
        pane_telaprincipal.setLayout(pane_telaprincipalLayout);
        pane_telaprincipalLayout.setHorizontalGroup(
            pane_telaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_telaprincipalLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(200, 200, 200))
        );
        pane_telaprincipalLayout.setVerticalGroup(
            pane_telaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_telaprincipalLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(200, 200, 200))
        );

        menu.setBackground(new java.awt.Color(0, 0, 0));

        menu_usuario.setText("Usuário");
        menu_usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_usuarioActionPerformed(evt);
            }
        });

        menuitem_login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuitem_login.setText("Login");
        menuitem_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_loginActionPerformed(evt);
            }
        });
        menu_usuario.add(menuitem_login);

        menu.add(menu_usuario);

        jMenu1.setText("|");
        jMenu1.setEnabled(false);
        jMenu1.setFocusable(false);
        menu.add(jMenu1);

        menu_opcoes.setText("Opções");
        menu_opcoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuitem_sobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuitem_sobre.setText("Sobre");
        menuitem_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_sobreActionPerformed(evt);
            }
        });
        menu_opcoes.add(menuitem_sobre);

        menuitem_ajuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuitem_ajuda.setText("Ajuda");
        menu_opcoes.add(menuitem_ajuda);

        menu.add(menu_opcoes);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_telaprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_telaprincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_sobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuitem_sobreActionPerformed

    private void menu_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_usuarioActionPerformed

    private void menuitem_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_loginActionPerformed
        // TODO add your handling code here:
        telaCadUser = new tela_login(pane_telaprincipal, menu, menuitem_sobre);
        pane_telaprincipal.add(telaCadUser);
        telaCadUser.setVisible(true);
        
        
    }//GEN-LAST:event_menuitem_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel logo;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menu_opcoes;
    private javax.swing.JMenu menu_usuario;
    private javax.swing.JMenuItem menuitem_ajuda;
    private javax.swing.JMenuItem menuitem_login;
    private javax.swing.JMenuItem menuitem_sobre;
    private javax.swing.JDesktopPane pane_telaprincipal;
    // End of variables declaration//GEN-END:variables
}
