/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package archdoc.docmanager;
import java.awt.Frame;
import java.awt.event.ComponentListener;
import java.sql.Connection;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JMenuBar;
import javax.swing.JFrame;
/**
 *
 * @author super
 */
public class tela_login extends javax.swing.JInternalFrame {

        
    /**
     * Creates new form tela_login
     */
    JDesktopPane telaPrincipal;
    boolean fezLogin = false;
    Connection conexao;
    connect criaBD;
    
    
    public tela_login(JDesktopPane telaPrincipal, Connection conexao) {
        initComponents();
        
        this.telaPrincipal = telaPrincipal;
        this.conexao = conexao;
        criaBD = new connect();
        
        int lDesk = telaPrincipal.getWidth();  
	int aDesk = telaPrincipal.getHeight();  
	int lIFrame = this.getWidth();  
	int aIFrame = this.getHeight();  

	this.setLocation(lDesk / 2 - lIFrame / 2, aDesk / 2 - aIFrame / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane_telalogin = new javax.swing.JPanel();
        campo_usuario = new javax.swing.JTextField();
        label_usuario = new javax.swing.JLabel();
        label_senha = new javax.swing.JLabel();
        botao_entrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        notas = new javax.swing.JTextPane();
        label_notas = new javax.swing.JLabel();
        campo_senha = new javax.swing.JPasswordField();

        setClosable(true);

        pane_telalogin.setBackground(new java.awt.Color(153, 153, 153));

        campo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_usuarioActionPerformed(evt);
            }
        });

        label_usuario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label_usuario.setText("Usuário");

        label_senha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label_senha.setText("Senha");

        botao_entrar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        botao_entrar.setText("ENTRAR");
        botao_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_entrarActionPerformed(evt);
            }
        });

        notas.setEditable(false);
        notas.setFocusable(false);
        jScrollPane1.setViewportView(notas);

        label_notas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label_notas.setText("Notas");

        javax.swing.GroupLayout pane_telaloginLayout = new javax.swing.GroupLayout(pane_telalogin);
        pane_telalogin.setLayout(pane_telaloginLayout);
        pane_telaloginLayout.setHorizontalGroup(
            pane_telaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_telaloginLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pane_telaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botao_entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(label_senha)
                    .addComponent(campo_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(label_usuario)
                    .addComponent(campo_senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(pane_telaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_notas))
                .addGap(80, 80, 80))
        );
        pane_telaloginLayout.setVerticalGroup(
            pane_telaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_telaloginLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pane_telaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_usuario)
                    .addComponent(label_notas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pane_telaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pane_telaloginLayout.createSequentialGroup()
                        .addComponent(campo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(botao_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_telalogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_telalogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrarActionPerformed
        // TODO add your handling code here
        
        char[] password = campo_senha.getPassword();
        
        if(criaBD.checkUser(conexao, campo_usuario.getText(), String.valueOf(password))){
	    tela_trabalho trab = new tela_trabalho();
            dispose();
            trab.setVisible(true);

            this.fezLogin = true;
            
            for(Frame v : tela_principal.getFrames()){
                   if(v.getName().equals("frame0")) v.dispose();
            }
	}
    }//GEN-LAST:event_botao_entrarActionPerformed

    private void campo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_usuarioActionPerformed

    public boolean isFezLogin() {
        return fezLogin;
    }

    public void setFezLogin(boolean fezLogin) {
        this.fezLogin = fezLogin;
    }

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_entrar;
    private javax.swing.JPasswordField campo_senha;
    private javax.swing.JTextField campo_usuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_notas;
    private javax.swing.JLabel label_senha;
    private javax.swing.JLabel label_usuario;
    private javax.swing.JTextPane notas;
    private javax.swing.JPanel pane_telalogin;
    // End of variables declaration//GEN-END:variables
}
