/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package archdoc.docmanager;

import java.awt.Desktop;
import java.io.File;

/**
 *
 * @author super
 */
public class tela_trabalho extends javax.swing.JFrame {

    /**
     * Creates new form tela_inicial
     */
    
    private String htmlSobre = System.getProperty("user.dir") + "\\HTML\\Sobre\\index.html";
    private String htmlAjuda = System.getProperty("user.dir") + "\\HTML\\Ajuda\\index.html";
    private tiposArquivos popup_tiposArquivos;
    
    public tela_trabalho() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
	
	tela_trabalho1 trabalhoNovo = new tela_trabalho1();
	pane_telaprincipal.add(trabalhoNovo);
	trabalhoNovo.setVisible(true);
	
	tela_trabalho2 trabalhoAtual = new tela_trabalho2();
	pane_telaprincipal.add(trabalhoAtual);
	trabalhoAtual.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane_telaprincipal = new javax.swing.JDesktopPane();
        menu_telatrabalho = new javax.swing.JMenuBar();
        menutrabalho_logo = new javax.swing.JMenu();
        menutrabalho_separador1 = new javax.swing.JMenu();
        menutrabalho_salvar = new javax.swing.JMenu();
        menutrabalho_separador2 = new javax.swing.JMenu();
        menutrabalho_exportar = new javax.swing.JMenu();
        menutrabalho_separador3 = new javax.swing.JMenu();
        menutrabalho_novoarquivo = new javax.swing.JMenu();
        menutrabalho_separador4 = new javax.swing.JMenu();
        menutrabalho_workpath = new javax.swing.JMenu();
        menutrabalho_separador5 = new javax.swing.JMenu();
        menutrabalho_opcoes = new javax.swing.JMenu();
        menuItem_Tipos = new javax.swing.JMenuItem();
        menuitem_sobre = new javax.swing.JMenuItem();
        menuitem_ajuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pane_telaprincipalLayout = new javax.swing.GroupLayout(pane_telaprincipal);
        pane_telaprincipal.setLayout(pane_telaprincipalLayout);
        pane_telaprincipalLayout.setHorizontalGroup(
            pane_telaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        pane_telaprincipalLayout.setVerticalGroup(
            pane_telaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        menutrabalho_logo.setText("AD.LMTD");
        menutrabalho_logo.setFocusable(false);
        menutrabalho_logo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_telatrabalho.add(menutrabalho_logo);

        menutrabalho_separador1.setText("|");
        menutrabalho_separador1.setEnabled(false);
        menutrabalho_separador1.setFocusable(false);
        menu_telatrabalho.add(menutrabalho_separador1);

        menutrabalho_salvar.setText("Salvar");
        menutrabalho_salvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_telatrabalho.add(menutrabalho_salvar);

        menutrabalho_separador2.setText("|");
        menutrabalho_separador2.setEnabled(false);
        menutrabalho_separador2.setFocusable(false);
        menu_telatrabalho.add(menutrabalho_separador2);

        menutrabalho_exportar.setText("Exportar Histórico");
        menutrabalho_exportar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_telatrabalho.add(menutrabalho_exportar);

        menutrabalho_separador3.setText("|");
        menutrabalho_separador3.setEnabled(false);
        menutrabalho_separador3.setFocusable(false);
        menu_telatrabalho.add(menutrabalho_separador3);

        menutrabalho_novoarquivo.setText("Novos Arquivos");
        menutrabalho_novoarquivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_telatrabalho.add(menutrabalho_novoarquivo);

        menutrabalho_separador4.setText("|");
        menutrabalho_separador4.setEnabled(false);
        menutrabalho_separador4.setFocusable(false);
        menu_telatrabalho.add(menutrabalho_separador4);

        menutrabalho_workpath.setText("WorkPath");
        menutrabalho_workpath.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_telatrabalho.add(menutrabalho_workpath);

        menutrabalho_separador5.setText("|");
        menutrabalho_separador5.setEnabled(false);
        menutrabalho_separador5.setFocusable(false);
        menu_telatrabalho.add(menutrabalho_separador5);

        menutrabalho_opcoes.setText("Opções");
        menutrabalho_opcoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItem_Tipos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItem_Tipos.setText("Configurar tipos");
        menuItem_Tipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem_TiposMouseClicked(evt);
            }
        });
        menuItem_Tipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_TiposActionPerformed(evt);
            }
        });
        menutrabalho_opcoes.add(menuItem_Tipos);

        menuitem_sobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuitem_sobre.setText("Sobre");
        menuitem_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_sobreActionPerformed(evt);
            }
        });
        menutrabalho_opcoes.add(menuitem_sobre);

        menuitem_ajuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuitem_ajuda.setText("Ajuda");
        menuitem_ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_ajudaActionPerformed(evt);
            }
        });
        menutrabalho_opcoes.add(menuitem_ajuda);

        menu_telatrabalho.add(menutrabalho_opcoes);

        setJMenuBar(menu_telatrabalho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_telaprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_telaprincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_sobreActionPerformed
        // TODO add your handling code here:
	try{
        Desktop desktop = Desktop.getDesktop();
	File htmlSobre_file = new File(htmlSobre);
        desktop.open(htmlSobre_file);
	}catch(Exception erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_menuitem_sobreActionPerformed

    private void menuItem_TiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem_TiposMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_menuItem_TiposMouseClicked

    private void menuItem_TiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_TiposActionPerformed
        // TODO add your handling code here:
	try{
	    if(!popup_tiposArquivos.isVisible()){
		popup_tiposArquivos = new tiposArquivos(pane_telaprincipal);
		pane_telaprincipal.add(popup_tiposArquivos);
		popup_tiposArquivos.setVisible(true);
		popup_tiposArquivos.moveToFront();
	    }
	}catch(Exception e){
	    popup_tiposArquivos = new tiposArquivos(pane_telaprincipal);
	    pane_telaprincipal.add(popup_tiposArquivos);
	    popup_tiposArquivos.setVisible(true);
	    popup_tiposArquivos.moveToFront();
	}
    }//GEN-LAST:event_menuItem_TiposActionPerformed

    private void menuitem_ajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_ajudaActionPerformed
        // TODO add your handling code here:
	try{
        Desktop desktop = Desktop.getDesktop();
	File htmlAjuda_file = new File(htmlAjuda);
        desktop.open(htmlAjuda_file);
	}catch(Exception erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_menuitem_ajudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_trabalho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem menuItem_Tipos;
    private javax.swing.JMenuBar menu_telatrabalho;
    private javax.swing.JMenuItem menuitem_ajuda;
    private javax.swing.JMenuItem menuitem_sobre;
    private javax.swing.JMenu menutrabalho_exportar;
    private javax.swing.JMenu menutrabalho_logo;
    private javax.swing.JMenu menutrabalho_novoarquivo;
    private javax.swing.JMenu menutrabalho_opcoes;
    private javax.swing.JMenu menutrabalho_salvar;
    private javax.swing.JMenu menutrabalho_separador1;
    private javax.swing.JMenu menutrabalho_separador2;
    private javax.swing.JMenu menutrabalho_separador3;
    private javax.swing.JMenu menutrabalho_separador4;
    private javax.swing.JMenu menutrabalho_separador5;
    private javax.swing.JMenu menutrabalho_workpath;
    private javax.swing.JDesktopPane pane_telaprincipal;
    // End of variables declaration//GEN-END:variables
}
