/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package archdoc.docmanager;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author conta
 */
public class tiposArquivos extends javax.swing.JInternalFrame {

    /**
     * Creates new form tiposArquivos
     */
    
    private String file = System.getProperty("user.dir") + "\\Parameters\\tiposArquivos.csv";
    
    public tiposArquivos(JDesktopPane tela) {
	initComponents();
	try{ atualizaTabela();
	}catch(Exception e) { ; }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaArquivos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSalvar = new javax.swing.JMenu();
        separar1 = new javax.swing.JMenu();
        menuCancelar = new javax.swing.JMenu();
        separar2 = new javax.swing.JMenu();
        menuDeletar = new javax.swing.JMenu();
        separar3 = new javax.swing.JMenu();
        menuAdicionar = new javax.swing.JMenu();

        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setVisible(true);

        tabelaArquivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "N°", "Tipo", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaArquivos);

        menuSalvar.setText("Salvar");
        jMenuBar1.add(menuSalvar);

        separar1.setText("|");
        separar1.setFocusable(false);
        jMenuBar1.add(separar1);

        menuCancelar.setText("Cancelar");
        jMenuBar1.add(menuCancelar);

        separar2.setText("|");
        separar2.setFocusable(false);
        jMenuBar1.add(separar2);

        menuDeletar.setText("Deletar");
        jMenuBar1.add(menuDeletar);

        separar3.setText("|");
        separar3.setFocusable(false);
        jMenuBar1.add(separar3);

        menuAdicionar.setText("Adicionar");
        menuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdicionarActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuAdicionar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdicionarActionPerformed
        // TODO add your handling code here:
	try{
	DefaultTableModel model = (DefaultTableModel) tabelaArquivos.getModel();
        
        String[] row = {
        String.valueOf(tabelaArquivos.getRowCount() + 1),
	JOptionPane.showInputDialog(null, "Digite o tipo de arquivo"),
	"S"
	};
	
        model.addRow(row);
	
	tabelaArquivos.setModel(model);
	
	}catch(Exception e){
	    System.out.println(e);
	}
    }//GEN-LAST:event_menuAdicionarActionPerformed

    private void atualizaTabela() throws FileNotFoundException, IOException{
	List<List<String>> tabela = new ArrayList<>();
	List<String> topo = new ArrayList<>();
	
	try (BufferedReader br = new BufferedReader(new FileReader(file))) {
	    String line;
	    while ((line = br.readLine()) != null) {
		String[] values = line.split(";");
		tabela.add(Arrays.asList(values));
	    }
	}
	
	int linha = 0, coluna = 0;
	
	for(List<String> i : tabela){
	    for(String w : i){
		coluna++;
		if(linha == 0){
		    topo.add(w);
		}
	    }
	    coluna = 0;
	    linha++;
	}
	
	tabela.remove(0);
	
	String[] tabelaString = topo.toArray(new String[0]);
	String[][] stringArray = tabela.stream().map(u -> u.toArray(new String[0])).toArray(String[][]::new);

	DefaultTableModel modo = new DefaultTableModel(stringArray, tabelaString);
	tabelaArquivos.setModel(modo);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuAdicionar;
    private javax.swing.JMenu menuCancelar;
    private javax.swing.JMenu menuDeletar;
    private javax.swing.JMenu menuSalvar;
    private javax.swing.JMenu separar1;
    private javax.swing.JMenu separar2;
    private javax.swing.JMenu separar3;
    private javax.swing.JTable tabelaArquivos;
    // End of variables declaration//GEN-END:variables
}
